# Generated by Django 5.1 on 2025-04-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_attendee_user_alter_attendee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], max_length=10),
        ),
    ]
