# Generated by Django 5.1 on 2025-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/default.jpg', null=True, upload_to='event_images/'),
        ),
    ]
