# Generated by Django 5.1 on 2025-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_event_requires_ticket_alter_event_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('VIP', 'VIP')], max_length=50, null=True),
        ),
    ]
